"""empty message

Revision ID: 037cbbf882ae
Revises: 
Create Date: 2024-01-13 23:48:49.131330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037cbbf882ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_value', sa.String(length=64), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('activeUEID', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ueid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meID', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('goal1_id', sa.Integer(), nullable=True),
    sa.Column('goal2_id', sa.Integer(), nullable=True),
    sa.Column('goal3_id', sa.Integer(), nullable=True),
    sa.Column('goal4_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goal1_id'], ['goal.id'], ),
    sa.ForeignKeyConstraint(['goal2_id'], ['goal.id'], ),
    sa.ForeignKeyConstraint(['goal3_id'], ['goal.id'], ),
    sa.ForeignKeyConstraint(['goal4_id'], ['goal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ueid')
    op.drop_table('meid')
    op.drop_table('goal')
    # ### end Alembic commands ###
